SELECT*
FROM CovidDeaths$
ORDER BY 3,4


SELECT*
FROM CovidVaccinations$_xlnm#_FilterDatabase
ORDER BY 3,4


SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION
FROM CovidDeaths$
ORDER BY 1,2

--LOOKING AT THE TOTAL CASES VS TOTAL DEATHS
--SHOWS THE LIKELIHOOD OF DYING IF YOU WERE TO CONTRACT COVID IN YOUR COUNTRY

SELECT LOCATION, DATE, TOTAL_CASES, TOTAL_DEATHS,(total_deaths/total_cases)*100 AS DEATHPERCENTAGE
FROM CovidDeaths$
WHERE LOCATION LIKE '%CAMEROON%'
ORDER BY 1,2 


--LOOKING AT THE TOTAL CASES VS POPULATION 
--SHOWS WHAT PERCENTAGE OF THE POPULATION HAS COVID 

SELECT LOCATION, DATE, TOTAL_CASES, population,(TOTAL_CASES/population)*100 AS PERCENTOFPOPULATIONINFECTED
FROM CovidDeaths$
WHERE LOCATION LIKE '%CAMEROON%'
ORDER BY 1,2 

--LOOKING AT COUNTRIES WITH THE HIGHEST INFECTION RATE COMPARED TO THE POPULATION

SELECT LOCATION, population, MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNT, MAX((TOTAL_CASES/population))*100 AS PERCENTOFPOPULATIONINFECTED
FROM CovidDeaths$
GROUP BY LOCATION, POPULATION 
ORDER BY PERCENTOFPOPULATIONINFECTED DESC


--SHOWING THE COUNTRIES WITH THE HIGHEST DEATHCOUNT PER POPULATION

SELECT LOCATION, MAX(CAST (total_deaths AS INT)) AS TOTALDEATHCOUNT
FROM CovidDeaths$
WHERE continent IS NOT NULL
GROUP BY LOCATION 
ORDER BY TOTALDEATHCOUNT DESC

--SHOWING CONTINENTS WITH THE HIGHEST DEATH COUNT PER POPULATION  
SELECT CONTINENT, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM CovidDeaths$
WHERE CONTINENT IS NOT NULL
GROUP BY continent
ORDER BY TOTALDEATHCOUNT DESC


--GLOBAL DEATHS 

SELECT SUM (NEW_CASES) AS TOTAL_CASES,SUM (CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATHS, SUM(CAST(NEW_DEATHS AS INT))/SUM (NEW_CASES)*100 AS DEATHPERCENTAGE
FROM CovidDeaths$
where continent is not null
order by 1,2


--LOOKING AT THE TOTAL POPULATON AGAINST THE TOTAL NUMBER OF VACCINATIONS

WITH POPVSVAC (CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINATIONS,SUMOFPEOPLEVACCINATED)
AS(
SELECT dea.continent, dea.location, dea.date, dea.population, vac.new_vaccinations
,sum(convert(int, vac.new_vaccinations)) over (partition by dea.location order by dea.location, dea.date) as sumofpeoplevaccinated
from CovidDeaths$ dea
join CovidVaccinations$_xlnm#_FilterDatabase vac
on dea.location = vac.location
and dea.date = vac.date
where dea.continent is not null
)
SELECT*, (sumofpeoplevaccinated/POPULATION)*100
FROM POPVSVAC



--CREATING VIEW TO STORE DATA FOR VISUALIZATION
CREATE VIEW PERCENTPOPULATIONVACCINATED AS
SELECT dea.continent, dea.location, dea.date, dea.population, vac.new_vaccinations
,sum(convert(int, vac.new_vaccinations)) over (partition by dea.location order by dea.location, dea.date) as sumofpeoplevaccinated
from CovidDeaths$ dea
join CovidVaccinations$_xlnm#_FilterDatabase vac
on dea.location = vac.location
and dea.date = vac.date
where dea.continent is not null

SELECT*
FROM PERCENTPOPULATIONVACCINATED 
